$("#rate_1").mouseover(function(){$("#rate_1").css("color","#ffd900")}),
$("#rate_1").mouseout(function(){$("#rate_1").css("color","#3c3c3c")}),
$("#rate_2").mouseover(function(){$("#rate_1, #rate_2").css("color","#ffd900")}),
$("#rate_2").mouseout(function(){$("#rate_1, #rate_2").css("color","#3c3c3c")}),
$("#rate_3").mouseover(function(){$("#rate_1, #rate_2, #rate_3").css("color","#ffd900")}),
$("#rate_3").mouseout(function(){$("#rate_1, #rate_2, #rate_3").css("color","#3c3c3c")}),
$("#rate_4").mouseover(function(){$("#rate_1, #rate_2, #rate_3, #rate_4").css("color","#ffd900")}),
$("#rate_4").mouseout(function(){$("#rate_1, #rate_2, #rate_3, #rate_4").css("color","#3c3c3c")}),
$("#rate_5").mouseover(function(){$("#rate_1, #rate_2, #rate_3, #rate_4, #rate_5").css("color","#ffd900")}),
$("#rate_5").mouseout(function(){$("#rate_1, #rate_2, #rate_3, #rate_4, #rate_5").css("color","#3c3c3c")})
